import { chromium } from 'file:///C:/Users/Lenovo/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
const outcomes=[];
async function begin(context){const p=await context.newPage();await p.goto('http://localhost:4173');await p.locator('#start-form button:not([disabled])').waitFor();await p.locator('#participant').fill('=测试,"01');await p.locator('#start-form button').click();return p;}
try{
  const c=await browser.newContext();await c.route('**/media/*.jpg',route=>route.abort());const p=await begin(c);await p.locator('#retry').waitFor();const before=await p.evaluate(()=>JSON.parse(localStorage.getItem('perception-study-session-v1')));
  assert.ok(before.events.some(e=>e.type==='stimulus_error'));await c.unroute('**/media/*.jpg');await p.locator('#retry').click();await p.waitForFunction(()=>!document.querySelector('#next').disabled);const after=await p.evaluate(()=>JSON.parse(localStorage.getItem('perception-study-session-v1')));assert.equal(before.trials[0].id,after.trials[0].id);assert.ok(after.events.some(e=>e.type==='stimulus_retry'));outcomes.push('network failure retry retains exact stimulus');
  const another=await c.newPage();await another.goto('http://localhost:4173');await another.getByText('实验已在另一个标签页打开').waitFor();await another.close();outcomes.push('second tab is prevented from overwriting session');
  await p.locator('#next').dblclick();await p.waitForFunction(()=>!document.querySelector('#next').disabled);assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('perception-study-session-v1')).index),1);outcomes.push('double click advances only once');
  await p.locator('#quit').click();await p.locator('#confirm-end').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('perception-study-session-v1')).status),'incomplete');const dl=p.waitForEvent('download');await p.locator('[data-export="json"]').click();assert.ok((await dl).suggestedFilename().endsWith('.json'));outcomes.push('early exit produces downloadable incomplete record');await c.close();
  const noStorage=await browser.newContext();await noStorage.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Blocked','QuotaExceededError');};});const ns=await begin(noStorage);await ns.locator('#storage-warning').waitFor({state:'visible'});await ns.locator('#quit').click();await ns.locator('#confirm-end').click();const memoryDownload=ns.waitForEvent('download');await ns.locator('[data-export="json"]').click();await memoryDownload;outcomes.push('storage failure shows warning and still exports from memory');await noStorage.close();
  const slow=await browser.newContext();await slow.route('**/media/*.jpg',async route=>{await new Promise(r=>setTimeout(r,900));await route.continue();});const sp=await begin(slow);await sp.waitForFunction(()=>!document.querySelector('#next').disabled);const timing=await sp.evaluate(()=>JSON.parse(localStorage.getItem('perception-study-session-v1')).trials[0]);assert.ok(timing.loadMs>=800);assert.ok(timing.visibleMs<timing.totalMs);outcomes.push('slow image loading is separated from visible time');await slow.close();
  console.log(JSON.stringify({passed:outcomes},null,2));
}finally{await browser.close();}
